
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░


input {
 # See https://wiki.hyprland.org/Configuring/Variables/#input
     kb_layout = us
     kb_options = caps:escape
     follow_mouse = 1
sensitivity = 1
  force_no_accel = false
#accel_profile = custom 200 0.0 0.5 2.0 5.0 10.0
     numlock_by_default = false
     # ~/.config/hypr/hyprland.conf

    # ... other settings like kb_layout ...
    # Sets how often the key repeats per second (default is usually 25)
    repeat_rate = 40

    # Sets the delay in ms before the repeat starts (default is usually 600)
    repeat_delay = 200

     touchpad {
 # See https://wiki.hyprland.org/Configuring/Variables/#touchpad
         natural_scroll = yes
     }
 }

decoration {
 fullscreen_opacity = 0.8
}

device {
  name = syna2ba6:00-06cb:ce44-touchpad
  sensitivity = 0.5
  scroll_factor = 2.5
}

general {
  layout = scroller
}

#bind = SUPER, tab, hyprtasking:toggle, cursor
#bind = SUPER SHIFT, tab, hyprtasking:toggle, all
## NOTE: the lack of a comma after hyprtasking:toggle!
#bind = , escape, hyprtasking:if_active, hyprtasking:toggle cursor
#
#
#bind = SUPER SHIFT, X, hyprtasking:killhovered
#
##bind = SUPER, H, hyprtasking:move, left
#bind = SUPER, J, hyprtasking:move, down
#bind = SUPER, K, hyprtasking:move, up
#bind = SUPER, L, hyprtasking:move, right

#plugin {
#    hyprtasking {
#        layout = grid
#
#        gap_size = 20
#        bg_color = 0xff26233a
#        border_size = 4
#        exit_on_hovered = false
#        warp_on_move_window = 1
#        close_overview_on_reload = true
#
#        drag_button = 0x110 # left mouse button
#        select_button = 0x111 # right mouse button
#        # for other mouse buttons see <linux/input-event-codes.h>
#
#        gestures {
#            enabled = false
#            move_fingers = 3
#            move_distance = 300
#            open_fingers = 4
#            open_distance = 300
#            open_positive = true
#        }
#
#        grid {
#            rows = 3
#            cols = 3
#            loop = false
#            gaps_use_aspect_ratio = false
#        }
#
#        linear {
#            height = 400
#            scroll_speed = 1.0
#            blur = false
#        }
#    }
#}
#

# Optional: Ensure it's in your cycle list (this is the default list)
plugin {
    scroller {
        column_widths = onethird onehalf twothirds one
    }
}
#bind = $mainMod, tab, scroller:toggleoverview
# Switch to Row mode (Horizontal scrolling)

bind = $mainMod, r, exec, ~/.config/hypr/scripts/hyprscroller_mode.sh
# Switch to Column mode (Vertical stacking)
bind = $mainMod shift, P, scroller:pin

exec-once = hyprpm reload -n
exec-once = [workspace 3] qutebrowser
exec-once = [workspace 3] kitty
exec-once = [workspace 2] yazi
exec-once = [worlspace 1] obsidian
exec-once = [worlspace 1] kitty 
#exec-once = [worlspace 4 silent] windscribe
exec-once = xremap .config/xremap/config.yml
# --- Autostart Scripts ---
# Execute the script to mount the Windows partition at startup
exec-once = ~/.config/hypr/scripts/mount_windows.sh
exec-once = hyprsunset
exec-once = fcitx5 -d
exec-once = ollama serve
# gestures {
# # See https://wiki.hyprland.org/Configuring/Variables/#gestures
#     workspace_swipe = true
#     workspace_swipe_fingers = 3
# }

